
server:
  port: 800

spring:
  devtools:
    restert:
      enabled: true


  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://localhost:3306/investitii?serverTimezone=UTC"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    hibernate:
      ddl-auto: "update"
file:
  read file: "/resources/adminZone/";
  write file: "/resources/adminZone/";